# Generated by Django 5.2.7 on 2025-11-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='CarModel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Model',
        ),
        migrations.AlterField(
            model_name='car',
            name='Power',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
