# Generated by Django 5.2.7 on 2025-11-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_car_brand_remove_car_carmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='add_car',
            new_name='CreatedAt',
        ),
    ]
