# Generated by Django 5.2.7 on 2025-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_add_car_car_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
