# Generated by Django 5.2.7 on 2025-11-26 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='Product',
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(default='Procesare', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='Car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='Carrier',
            field=models.CharField(default='Fan Courier', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='EstimatedArrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='Status',
            field=models.CharField(default='În tranzit', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='IBAN',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name='order',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Method',
            field=models.CharField(default='Transfer bancar', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='PaymentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='Shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.shipment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='TrackNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
