# Generated by Django 5.2.7 on 2025-11-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_shipment_product_order_status_review_car_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
